
CREATE SEQUENCE MEMBER_SEQ;
CREATE TABLE MEMBER(
	MEMBER_SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(200) UNIQUE NOT NULL,
	PW VARCHAR2(500) NOT NULL,
	ENABLE NUMBER  NOT NULL,
	AUTHORITY VARCHAR2(200)	NOT NULL,
	NICKNAME VARCHAR2(200) NOT NULL,
	EMAIL VARCHAR2(200) NOT NULL,
	CATEGORYS VARCHAR2(500),
	PROFILE_IMG VARCHAR2(200),
	END_DATE DATE

);




CREATE TABLE CATEGORY(
	CATEGORY_CODE VARCHAR2(20),
	CATEGORY_NAME VARCHAR2(20) NOT NULL,
	
	CONSTRAINT CATEGORY_CODE_TE_PK PRIMARY KEY(CATEGORY_CODE)
);

CREATE SEQUENCE BOARD_LECTURE_SEQ;
CREATE TABLE BOARD_LECTURE(
	BOARD_LECTURE_SEQ NUMBER,
	CATEGORY_CODE VARCHAR2(20) NOT NULL,
	TUTER_ID VARCHAR2(20) NOT NULL,
	BOARD_LECTURE_CONTENT VARCHAR2(2000) NOT NULL,
	BOARD_LECTURE_REGDATE DATE NOT NULL,
	BOARD_LECTURE_TAG VARCHAR2(50) NOT NULL,
	BOARD_LECTURE_IMAGE VARCHAR2(100) NOT NULL,
	BOARD_LECTURE_STAR_TOTAL NUMBER,
	BOARD_LECTURE_STAR_COUNT NUMBER,
	
	CONSTRAINT BOARD_LECTURE_SEQ_TE_PK PRIMARY KEY(BOARD_LECTURE_SEQ),
	CONSTRAINT CATEGORY_CODE_TE_FK FOREIGN KEY(CATEGORY_CODE) REFERENCES CATEGORY(CATEGORY_CODE),
	CONSTRAINT TUTER_ID_TE_FK FOREIGN KEY(TUTER_ID) REFERENCES MEMBER(ID)
);


CREATE SEQUENCE BOARD_VOD_SEQ;
CREATE TABLE BOARD_VOD(
	BOARD_VOD_SEQ NUMBER,
	BOARD_LECTURE_SEQ NUMBER NOT NULL,
	BOARD_VOD_CONTENT VARCHAR2(2000) NOT NULL,
	BOARD_VOD_REGDATE DATE NOT NULL,
	BOARD_VOD_IMAGE VARCHAR2(100) NOT NULL,
	BOARD_VOD_STAR_TOTAL NUMBER,
	BOARD_VOD_STAR_COUNT NUMBER,
	
	CONSTRAINT BOARD_VOD_SEQ_CATEGORY_PK PRIMARY KEY(BOARD_VOD_SEQ),
	CONSTRAINT BOARD_LECTURE_SEQ_CATEGORY_FK FOREIGN KEY(BOARD_LECTURE_SEQ) REFERENCES BOARD_LECTURE(BOARD_LECTURE_SEQ)
);

CREATE SEQUENCE REVIEW_SEQ;
CREATE TABLE REVIEW(
	REVIEW_SEQ NUMBER,
	BOARD_LECTURE_SEQ NUMBER NOT NULL,
	ID VARCHAR2(20) NOT NULL,
	REVIEW_CONTENT VARCHAR2(500) NOT NULL,
	REVIEW_REGDATE DATE NOT NULL,
	
	CONSTRAINT REVIEW_SEQ_REVIEW_PK PRIMARY KEY(REVIEW_SEQ),
	CONSTRAINT BOARD_LECTURE_SEQ_REVIEW_FK FOREIGN KEY(BOARD_LECTURE_SEQ) REFERENCES BOARD_LECTURE(BOARD_LECTURE_SEQ),
	CONSTRAINT ID_REVIEW_FK FOREIGN KEY(ID) REFERENCES MEMBER(ID)
);

CREATE SEQUENCE CALENDAR_SEQ;
CREATE TABLE CALENDAR(
	CALENDAR_SEQ NUMBER,
	ID VARCHAR2(20) NOT NULL,
	CALENDAR_TITLE VARCHAR2(20) NOT NULL,
	CALENDAR_CATEGORY VARCHAR2(40),
	CALENDAR_DESCRIPTION VARCHAR2(200),
	CALENDAR_START DATE NOT NULL,
	CALENDAR_END DATE NOT NULL,
	
	CONSTRAINT CALENDAR_SEQ_CALENDAR_PK PRIMARY KEY(CALENDAR_SEQ),
	CONSTRAINT ID_CALENDAR_FK FOREIGN KEY(ID) REFERENCES MEMBER(ID)
);

INSERT INTO CALENDAR VALUES(CALENDAR_SEQ.NEXTVAL, 'TITLE1', 'CATEGORY1', 'DESCRIPTION1', '2019-10-14', NULL);

CREATE SEQUENCE ROOM_LECTURE_SEQ;
CREATE TABLE ROOM_LECTURE(
	ROOM_LECTURE_SEQ NUMBER,
	TUTOR VARCHAR2(20) NOT NULL,
	TUTEES VARCHAR2(500) NOT NULL,
	
	CONSTRAINT ROOM_LECTURE_SEQ_ROOM_PK PRIMARY KEY(ROOM_LECTURE_SEQ),
	CONSTRAINT TUTOR_ROOM_LECTURE_FK FOREIGN KEY(TUTOR) REFERENCES MEMBER(ID)
);

CREATE TABLE PAYMENT(
	ORDER_ID VARCHAR2(100),
	ID VARCHAR2(20) NOT NULL,
	ITEM_NAME VARCHAR2(50) NOT NULL,
	AMOUNT NUMBER NOT NULL,
	PAYMENT_DATE DATE NOT NULL,
	
	CONSTRAINT ORDER_ID_PAYMENT_PK PRIMARY KEY(ORDER_ID),
	CONSTRAINT ID_PAYMENT_FK FOREIGN KEY(ID) REFERENCES MEMBER(ID)
);

CREATE SEQUENCE MAP_SEQ;
CREATE TABLE MAP(
	MAP_SEQ NUMBER,
	X_POINT VARCHAR2(50) NOT NULL,
	Y_POINT VARCHAR2(50) NOT NULL,
	
	CONSTRAINT MAP_SEQ_MAP_PK PRIMARY KEY(MAP_SEQ)
);

