DROP SEQUENCE MEMBER_SEQ;
DROP TABLE MEMBER;

DROP TABLE CATEGORY;

DROP SEQUENCE BOARD_LECTURE_SEQ;
DROP TABLE BOARD_LECTURE;

DROP SEQUENCE BOARD_VOD_SEQ;
DROP TABLE BOARD_VOD;

DROP SEQUENCE REVIEW_SEQ;
DROP TABLE REVIEW;

DROP SEQUENCE CALENDAR_SEQ;
DROP TABLE CALENDAR;

DROP SEQUENCE ROOM_LECTURE_SEQ;
DROP TABLE ROOM_LECTURE;

DROP TABLE PAYMENT;

DROP SEQUENCE MAP_SEQ;
DROP TABLE MAP;